### ISSUE TITLE
Make doctrine/inflector constraint less strict.

### ISSUE THREAD

**Issue by nicksantamaria** [CSharpRU/vault-php#14]
I'm unable to install this library in a Drupal 8.5.x application as there is a conflict on the dependency `doctrine/inflector`.

Changing the version constraint from `~1.1.0` to `~1.1` resolves this issue for me.

I can see this was intentionally set in this commit - https://github.com/CSharpRU/vault-php/commit/b7fc83d2174d35a5222da60230fdfaf6a0ed0192

Is there a specific issue which necessitated this? If so, is it a bug that can be resolved in this library?

https://github.com/CSharpRU/vault-php/blob/04be9776310fe7d1afb97795645f95c21e6b4fcf/composer.json#L21

**Comment by CSharpRU** [comment]
Hi!

Yep, there was a bug related with doctrine/inflector, but I don't remember what it was about. Let me check it again and I'll change constraint.
