### ISSUE TITLE
Can not find the Guzzle6Transport class

### ISSUE THREAD

**Issue by sunrise9527** [CSharpRU/vault-php#18]
When I call the `new Client(new Guzzle6Transport())`, there is an error that can not find Guzzle6Transport class
 so I have to download the `composer require csharpru/vault-php-guzzle6-transport` manually.

**Comment by CSharpRU** [comment]
Hello there,

Yes, you have to download it manually until issue https://github.com/CSharpRU/vault-php/issues/3 is not resolved.
