### ISSUE TITLE
How long until it is stable?

### ISSUE THREAD

**Issue by joaquinbravo-natgeo** [CSharpRU/vault-php#20]
The warning in the README.txt is from August of 2017. Is it still an unstable project? Or is it there a RC planned?

**Comment by CSharpRU** [comment]
Hello there,

Right now the last version of this project is working inside several production applications without problems. You can try it as well, but I'm planning major changes to the library's API, installation procedure, tests and other important parts (RC will be planned after). If you want to use it just fix the version up to 3.6.x.

**Comment by tomasnorre** [comment]
What is the status of this? 

With version 4.1.0 I would expect it to be production-ready.

**Comment by IMSoP** [comment]
I don't think "production-ready" and "planning major API changes" need to be mutually exclusive - you can always tag 5.0.0, 6.0.0, etc, and tell us what you've changed.

If it's in use in production, and has gone through several major versions already, I think it's time to believe in yourself, and remove the warning. 🙂 If there's certain parts that are less "battle-tested" than others, then you could label those, which is more useful than a general warning anyway.

**Comment by hexa2k9** [comment]
As when it comes to me the dependency is used in one hell of a major project I'm working with. I see thousands of interactions with the library each day and given you know how you Vault Instance "looks like" it's safe to assume It's one piece of solid work which never gave me trouble.

Thanks for that @CSharpRU!

**Comment by CSharpRU** [comment]
I think it's safe to consider current state as stable (in production from my side for several years, no major bug reports).

Thanks everyone! :)
