### ISSUE TITLE
Consider using php-http

### ISSUE THREAD

**Issue by soullivaneuh** [CSharpRU/vault-php#22]
PHP-HTTP is used by many libraries to get rid of transport management using an abstraction: http://docs.php-http.org/en/latest/

Basically, with that, you don't need to maintain your Guzzle transports anymore and you let the possibility to the user to use the transport he wants: http://docs.php-http.org/en/latest/clients.html

Plus, it will reduce dependencies on end project.

Regards

**Comment by CSharpRU** [comment]
Hello @Soullivaneuh,

Thanks for the reporting, I've already implemented PSR-18 in https://github.com/CSharpRU/vault-php/pull/19, but have no time to test it properly.

**Comment by Soullivaneuh** [comment]
Indeed, implementing PSR-18 only is event better to let the user choice. Thanks!

**Comment by CSharpRU** [comment]
PSR-18 code is merged into the develop branch, but it should be tested somewhere in a production environment.
