### ISSUE TITLE
Transport folder missing after composer require

### ISSUE THREAD

**Issue by derekyle** [CSharpRU/vault-php#26]
I don't know enough about Composer to know if this is an issue with your repo or an issue with composer, but when I do a composer require for your project, the "transports" folder is missing. Which is of course causing an error when the guzzle6transport file tries to call it:

"PHP Fatal error:  Uncaught Error: Interface 'Vault\Transports\Transport' not found"

**Comment by CSharpRU** [comment]
Hello there, try to use 4.0.0 version and any PSR-18 compatible transport.
