### ISSUE TITLE
Update doctrine / inflector

### ISSUE THREAD

**Issue by Fulmenef** [CSharpRU/vault-php#27]
Hi, 
We can't install a dependency which use this project because we have another dependency which use the latest version of [doctrine/inflector](https://github.com/doctrine/inflector).

I see this project use a strict version (~1.1) of [doctrine/inflector](https://github.com/doctrine/inflector). In #14 it is said that there was a bug at this time.

Is there any plan to test with the new version (1.3.1) and maybe update it ?

**Comment by CSharpRU** [comment]
Hi there, sorry for delay.

I'll look into it to update inflector package.
