### ISSUE TITLE
Please release version without cache/cache dependencies

### ISSUE THREAD

**Issue by marcusirgens** [CSharpRU/vault-php#37]
See https://github.com/magento/magento2-functional-testing-framework/pull/723 :) 
I notice this is already done on master branch, it probably just needs to be tagged and pushed.

**Comment by CSharpRU** [comment]
https://github.com/CSharpRU/vault-php/blob/4.1.0/composer.json

**Comment by marcusirgens** [comment]
Thank you very much @CSharpRU :)
