### ISSUE TITLE
[Question] "Zend/Diactoros" has been abandoned 2019-12-31

### ISSUE THREAD

**Issue by menturion** [CSharpRU/vault-php#40]
Hi, 

I have seen that the examples & tests given are using "Zend/Diactoros" which has been abandoned 2019-12-31. 
The repo has been moved to "laminas/laminas-diactoros". 

Are there already any tests replacing "Zend/Diactoros" with "laminas/laminas-diactoros"? 

Do you still recommend to use "Zend/Diactoros"?

**Comment by IMSoP** [comment]
In case anyone reading wasn't aware, the background here is that the company that owns the "Zend" trademark is no longer supporting the Zend Framework and associated projects, so they have been re-formed under a new name and organization as "Laminas". 

I imagine the new package is a drop-in replacement, although presumably namespaces have been changed to match the new project name.

**Comment by CSharpRU** [comment]
Replaced with laminas package.
