### ISSUE TITLE
PHP8 Support

### ISSUE THREAD

**Issue by Luca-Castelnuovo** [CSharpRU/vault-php#47]
Hi, currently when installing on PHP8 I get this error:
<img width="818" alt="Screenshot 2021-02-20 at 14 02 39" src="https://user-images.githubusercontent.com/26206253/108596283-4bd41680-7384-11eb-999e-7952454488f4.png">

Would it be possible to add PHP8 support?

**Comment by Luca-Castelnuovo** [comment]
I build a PHP8 version, it currently only supports AppRole and Token.
But hopefully it can help someone https://github.com/CubeQuence/vault

**Comment by CSharpRU** [comment]
Hello! You could use 4.2 for PHP8 support :)
